apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml

images:
  - name: ghcr.io/pixcorp/cloud-sentinel-k8s-backend
    newName: ghcr.io/pixcorp/cloud-sentinel-k8s
    # x-release-please-start-version
    newTag: 1.8.0
    # x-release-please-end
