apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - frontend.yaml

images:
  - name: ghcr.io/pixcorp/cloud-sentinel-k8s-backend
    newName: ghcr.io/pixcorp/cloud-sentinel-k8s-backend
    # x-release-please-start-version
    newTag: 1.6.0
    # x-release-please-end
  - name: ghcr.io/pixcorp/cloud-sentinel-k8s-frontend
    newName: ghcr.io/pixcorp/cloud-sentinel-k8s-frontend
    # x-release-please-start-version
    newTag: 1.6.0
    # x-release-please-end
